apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
  labels:
    app: nodejs-app
spec:
  selector:
    app: nodejs-app
  ports:
  - protocol: TCP
    port: 80          # Port exposed by the service
    targetPort: 8000  # Port in the container
  type: LoadBalancer  # Exposes the service to an external IP
